[package]
name = "f1-track"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "2.0"
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
actix-files = "0.6"
